/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastro.clientes;

/**
 *
 * @author Guilherme Gamarelle
 */
public class Tela extends javax.swing.JFrame {
   
 String nome;
    String cpf;
    private int sexo;
    String endereço;
    String estado;
    String cidade;
     
  
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        CampoEstado = new javax.swing.JTextField();
        CampoCPF = new javax.swing.JTextField();
        CampoIdade = new javax.swing.JTextField();
        CampoNumero = new javax.swing.JTextField();
        CampoRua = new javax.swing.JTextField();
        CampoCidade = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 40, 30);

        jLabel2.setText("Cidade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 220, 33, 14);

        jLabel3.setText("Estado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 40, 50, 30);

        jLabel4.setText("CPF");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 80, 40, 20);

        jLabel5.setText("Idade");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 100, 30, 40);

        jLabel6.setText("Rua");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 170, 40, 30);

        jLabel7.setText("Sexo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 250, 60, 40);

        jLabel8.setText("Nº");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 150, 12, 14);
        getContentPane().add(CampoNome);
        CampoNome.setBounds(90, 20, 50, 20);
        getContentPane().add(CampoEstado);
        CampoEstado.setBounds(90, 50, 50, 20);
        getContentPane().add(CampoCPF);
        CampoCPF.setBounds(80, 80, 60, 20);
        getContentPane().add(CampoIdade);
        CampoIdade.setBounds(70, 110, 70, 20);
        getContentPane().add(CampoNumero);
        CampoNumero.setBounds(70, 140, 60, 20);
        getContentPane().add(CampoRua);
        CampoRua.setBounds(70, 180, 60, 20);
        getContentPane().add(CampoCidade);
        CampoCidade.setBounds(70, 220, 60, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino ", "Outros", " " }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(80, 260, 110, 30);

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 270, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.nome = CampoNome.getText();
        this.cidade = CampoCidade.getText();
        this.cpf = CampoCPF.getText();
        this.endereço = CampoRua.getText();
        this.estado = CampoEstado.getText();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCPF;
    private javax.swing.JTextField CampoCidade;
    private javax.swing.JTextField CampoEstado;
    private javax.swing.JTextField CampoIdade;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoNumero;
    private javax.swing.JTextField CampoRua;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
